CREATE DATABASE IF NOT EXISTS maindb;
USE maindb;
CREATE TABLE IF NOT EXISTS connections (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user VARCHAR(255) NOT NULL,
	repo VARCHAR(255) NOT NULL,
    currentVersion VARCHAR(255) NOT NULL,
	previousVersion VARCHAR(255) NOT NULL);
	