CREATE DATABASE IF NOT EXISTS maindb;
USE maindb;
CREATE TABLE IF NOT EXISTS entries (
	id INT AUTO_INCREMENT PRIMARY KEY,
	chatID VARCHAR(255) NOT NULL,
	repoName VARCHAR(255) NOT NULL,
	repoLink VARCHAR(255) NOT NULL,
	currentReleaseTagName VARCHAR(255),
    currentReleaseID VARCHAR(255),
	previousReleaseID VARCHAR(255));
	